name: Deploy BaitCalc

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ↗️
    runs-on: ubuntu-latest

    steps:
      # 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@master

      # 2: Sync files to hosting server (excluding vendor)
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ssh_host }}
          username: f0170c88
          password: ${{ secrets.ftp_password }}

      # 3: Run Composer on live server
      - name: Install Composer dependencies
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ssh_host }}
          username: ${{ secrets.ssh_username }}
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            cd www/htdocs/w00866af/baitcalc.computer-area.net
            
            if [ ! -f composer.phar ]; then
              curl -sS https://getcomposer.org/installer | php
            fi
            
            /usr/bin/php82 composer.phar install --no-dev --optimize-autoloader

      # 4: execute Yii2 migrations
      - name: Run Yii2 migrations on live server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ssh_host }}
          username: ${{ secrets.ssh_username }}
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            cd www/htdocs/w00866af/baitcalc.computer-area.net

            /usr/bin/php82 yii migrate --interactive=0

      # 5: Flush Yii2 cache
      - name: Flush Yii2 cache
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ssh_host }}
          username: ${{ secrets.ssh_username }}
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            cd www/htdocs/w00866af/baitcalc.computer-area.net
            
            /usr/bin/php82 yii cache/flush-all
